// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    NavItems: typeof import('./src/components/NavItems.vue')['default']
    ZScrollContainer: typeof import('./src/components/ZScroll/ZScrollContainer.vue')['default']
    ZScrollItem: typeof import('./src/components/ZScroll/ZScrollItem.vue')['default']
  }
}

export { }
