query microBlogs {
  repository(owner: "AllanChain", name: "micro-blog") {
    discussions(categoryId: "DIC_kwDOGw6A_84CA774", first: 10) {
      nodes {
        title
        createdAt
        updatedAt
        comments(first: 100) {
          nodes {
            author {
              login
            }
            url
            body
            createdAt
            updatedAt
            upvoteCount
            reactions (first: 4) {
              totalCount
              nodes {
                user {
                  login
                }
              }
            }
            replies(first: 20) {
              nodes {
                author {
                  login
                  ... on User {
                    name
                  }
                }
                body
                createdAt
                updatedAt
              }
            }
          }
        }
      }
    }
  }
}
