name: Build Site on Blog Change

on:
  discussion_comment:
    types: [created, edited, deleted]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  discussions: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build the Pages
    runs-on: ubuntu-latest
    if: github.event.sender.login == 'AllanChain'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: app/dist
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: blog-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            blog-${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.8.0
          run_install: |
            cwd: graphql
      - run: pnpm data:dist
        working-directory: graphql
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: app/dist

  deploy:
    name: Deploy the Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
